### ISSUE TITLE
Authentication / accounts

### ISSUE THREAD

**Issue by jordaneremieff** [erm/guitarlette#2]
Implement authentication and accounts.

It is a bit beyond what I'm currently doing here, but it would be cool to have this deployed as a service that other people could use. At the very least it could serve as an example of how to do authentication with Starlette.

**Comment by sjortiz** [comment]
I would like to work on this, do you have more details on this matter, which kind of auth would you like to have in here? E.g.: Implicit?, basic auth?

Would you like to have user groups? if so it will be spliced across different submissions
Do you want to limit access for users as groups or by individuals?
Will such access be by endpoint or by roles?

Best regards

**Comment by jordaneremieff** [comment]
@sjortiz I don't have any strong preferences as to the particulars, but ideally I think this could serve a community platform in addition to a personal notebook. I haven't really had a chance to explore the auth aspect at this point, do you have any suggestions?

**Comment by sjortiz** [comment]
we can start with basic auth and build on top to extend the methods later

**Comment by jordaneremieff** [comment]
@sjortiz sounds good. Haven't had a lot of time to work on this, but if you put forward a PR I can take a look.
